[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/boats/refresh"
  to = "/.netlify/functions/boats-refresh"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/boats/*"
  to = "/.netlify/functions/boats?id=:splat"
  status = 200
  force = true